- name: Set authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_keys }}"

- name: disable root login
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^PermitRootLogin
    line: PermitRootLogin no

- name: disable password login
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^PasswordAuthentication
    line: PasswordAuthentication no